# Copyright (c) Alexej Disterhoft <alexej@disterhoft.de>
# SPDX-License-Identifier: MPL-2.0

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
        args: []
